name: Node.js Build & Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Build project
        run: pnpm run build

      # 🔥 打包成你要的名字
      - name: Package
        run: zip -r napcat-plugin-offline-notification.zip dist/

      # 🔥 上传
      - name: Upload to Release
        uses: softprops/action-gh-release@v2
        with:
          files: napcat-plugin-offline-notification.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}